### ISSUE TITLE
Integrate gitcollector

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#47]
To integrate https://github.com/src-d/gitcollector we need:

- Add gitcollector to docker-compose file, use env vars for config.
- Create new sub commands. We don't have a final decision on this, but this is easy to rename at any time.
  - `sourced local init /path/to/repos`: the current `init`. It will need to run `docker-compose up` excluding the service for gitcollector
  - `sourced orgs init name-a,name-b,name-c`: new sub command to launch gitcollector and ghsync
- Manage the workdir for orgs. It's probably better to separate local and orgs, so we could have:
  - `~/.sourced/workdirs/fs/` + `path/to/dir`
  - `~/.sourced/workdirs/orgs/` + `<base64(org-a,org-b,org-c)>`

Side note: we may want to get the organizations argument in `sourced` and order them alphabetically. This way we'll have the same workspace for `src-d,bblfsh` and `bblfsh,src-d`

**Comment by carlosms** [comment]
Quoting @smacker from description in #51, for visibility:

> TODO in sequential PRs because this PR is rather big already:
> - rename `init` into `local init` #60
> - add validation for token and organization names correctness #59
> - there is initial support for multi-orgs but ghcollector supports only 1 for now. Most probably it also makes sense to sort them and maybe some other changes that are better to implement with underlying support is ready #61
> - move orgs workdirs into orgs subdir and local workdirs into local subdir (maybe)

**Comment by carlosms** [comment]
Also missing:
- documentation in README.
- Instructions to create the GH token

**Comment by dpordomingo** [comment]
I'd say that some of them are already done:
- [x] Rename the init commands #85
- [x] Validate params for orgs init #70
- [x] Add support for multiple organizations #63

And others pending to be approved:
- [x] documentation in README. #95
- [x] Instructions to create the GH token #95

I'd say the only one missing is:
- [ ] move orgs workdirs into orgs subdir and local workdirs into local subdir (maybe)

I'd suggest to close this issue, and create new issues for pending ones, and those that should be reworked.

**Comment by smacker** [comment]
done. Issue about workdir names: https://github.com/src-d/sourced-ce/issues/99
